### ISSUE TITLE
입상 축하드립니다. 질문이 있는데요.

### ISSUE THREAD

**Issue by ddobokki** [sangHa0411/skku-Sentence_Type_Classification#1]
아직 확정(?)이 안난걸로 알고는 있지만 그래도 되겠죠 아마?

다름이 아니라

```
Model Structure
CLS 토큰 이외에도 EOS 토큰의 출력을 Concat해서 Sequence Output으로 설정
```
이부분 말인데요.
CLS 토큰은 pos embedding이 항상 0으로 고정 되어서 clssification에서 사용 가능하다고 이해하고 있었는데 EOS를 concat해서 classification head에 넘겨준 것은 문장 길이에 대한 정보를 추가적으로 모델에게 알려주고 싶어서 그런 거라고 해석해도 될까요? 아니면 다른 이유가 있었을까요?

다시한번 입상 축하드립니다.

**Comment by sangHa0411** [comment]
안녕하세요!
사실 그렇게 까지 깊게 생각하지 않았는데 말씀해주신 내용도 맞는 것 같습니다.
저는 일단  Classification Head 를 좀 더 크게하자는 생각과 데이콘 코드 유사성 대회에서 해당 모델이 상당히 성능이
좋게 나왔다는 경험 때문이었습니다.

이 모델을 생각한 계기는 T5등에서는 CLS가 아닌 Encoder에서 EOS 토큰의 Feature을 Decoder로 보내기 때문에
NSP, SOP Loss등을 활용해서 사전학습을 하지 않은 모델이라면 충분히 CLS, EOS 모두 사용가능할 것이라고 생각했습니다.
실제로 코드유사성 대회에서는 [CLS] Sentence1 [SEP] Sentence 2 [SEP] Padding 이렇게 입력이 되면
CLS, SEP, SEP 등을 concat하거나 mean을 한 것이 단순히 CLS를 Sequence Output을 할 때 보다 성능이
상당히 높았습니다.

지금 생각해보니 SEP 및 EOS 등 을 사용하는 것이 말씀하신대로 문장 길이에 대한 정보를 추가적으로 줄 수 있기 때문에 성능이
향상된 것이 아닐까 생각이 듭니다.

감사합니다!




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
22.
12. 27. 오후 06:14:59

2022년 12월 27일 (화) 오후 3:19, ddobokki ***@***.***>님이 작성:

**Comment by ddobokki** [comment]
답변 감사합니다! 나중에 기회 되면 경진대회에서 또 봬요 ㅎㅎ
